package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildScanTestTagWithVersion'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildScanTestTagWithVersion")) {
    expectSteps {
    }
    steps {
        insert(0) {
            script {
                name = "Docker Buildx diagnostics"
                id = "Docker_Buildx_diagnostics"
                scriptContent = """
                    where docker
                    docker version
                    docker buildx version
                    docker buildx ls
                """.trimIndent()
            }
        }
        check(stepsOrder == arrayListOf<String>()) {
            "Unexpected build steps order: $stepsOrder"
        }
        stepsOrder = arrayListOf("Docker_Buildx_diagnostics", "RUNNER_895", "RUNNER_706", "RUNNER_896", "RUNNER_897")
    }
}
