package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildScanTestTagWithVersion'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildScanTestTagWithVersion")) {
    requirements {
        remove {
            equals("teamcity.agent.jvm.os.name", "Linux", "RQ_1")
        }
    }
}
