package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildScanTestTagWithVersion'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildScanTestTagWithVersion")) {
    expectSteps {
    }
    steps {
        check(stepsOrder == arrayListOf<String>()) {
            "Unexpected build steps order: $stepsOrder"
        }
        stepsOrder = arrayListOf("Docker_Buildx_diagnostics", "RUNNER_895", "RUNNER_706", "RUNNER_896", "RUNNER_897")
    }
}
