# Generated by Django 5.2.12 on 2026-07-13 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_uuid_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='delivery_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public UUID for this delivery (non-enumerable)', unique=True),
        ),
    ]
