# Generated by Django 5.2.17 on 2026-08-10 11:31

import django.db.models.deletion
from django.db import migrations, models


def link_reviewees_to_profiles(apps, schema_editor):
    Reviewee = apps.get_model("accounts", "Reviewee")
    UserProfile = apps.get_model("accounts", "UserProfile")
    for profile in UserProfile.objects.select_related("user").iterator():
        email = (profile.user.email or "").strip()
        if not email:
            continue
        Reviewee.objects.filter(
            organization_id=profile.organization_id,
            email__iexact=email,
            profile__isnull=True,
        ).update(profile_id=profile.id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_password_reset_token"),
        ("core", "0009_upgradestep"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewee",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewee",
                to="accounts.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="reviewee",
            name="reporting_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_report_reviewees",
                to="accounts.userprofile",
            ),
        ),
        migrations.RunPython(link_reviewees_to_profiles, migrations.RunPython.noop),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="core.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "db_table": "teams",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="reviewee",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewees",
                to="accounts.team",
            ),
        ),
        migrations.CreateModel(
            name="TeamLeadGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("include_descendants", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_lead_grants",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_grants",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_lead_grants",
            },
        ),
        migrations.CreateModel(
            name="TeamLeadRevocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revocations",
                        to="accounts.teamleadgrant",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_revocations",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_lead_revocations",
            },
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_team_name_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="teamleadgrant",
            constraint=models.UniqueConstraint(
                fields=("profile", "team"), name="unique_profile_team_lead_grant"
            ),
        ),
        migrations.AddConstraint(
            model_name="teamleadrevocation",
            constraint=models.UniqueConstraint(
                fields=("grant", "team"), name="unique_grant_team_revocation"
            ),
        ),
    ]
