# Generated by Django 5.2.17 on 2026-08-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_team_authorization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinvitation",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="accounts.team",
            ),
        ),
    ]
